### ISSUE TITLE
Input file generations

### ISSUE THREAD

**Issue by s-kyungyong** [sc-zhang/CATG#1]
Hi!

Could you clarify what the input files need to contain in the bed and anchor files? For instance, do I need to map my contigs my scaffolds and specify the coordinates of contigs? It would be great if you could provide a bit more detailed workflow for each of these files. 

Thank you!

```
head *.bed
==> qry.bed <==
Chr01   41145   41785   qry_00001       0       +
Chr01   59154   71715   qry_00002       0       -
Chr01   103208  111702  qry_00003       0       -
Chr01   149421  150851  qry_00004       0       -
Chr01   191873  224679  qry_00005       0       +
Chr01   250203  251891  qry_00006       0       +
Chr01   254140  255065  qry_00007       0       -
Chr01   266012  268537  qry_00008       0       +
Chr01   278218  283309  qry_00009       0       +
Chr01   284138  310323  qry_00010       0       -

==> ref.bed <==
Chr01   55738   61737   ref_00001       0       -
Chr01   106533  107844  ref_00002       0       -
Chr01   168873  170182  ref_00003       0       -
Chr01   202454  203895  ref_00004       0       -
Chr01   235032  236624  ref_00005       0       -
Chr01   273437  277531  ref_00006       0       +
Chr01   316293  318461  ref_00007       0       +
Chr01   332249  332956  ref_00008       0       -
Chr01   375185  385620  ref_00009       0       +
Chr01   388537  389590  ref_00010       0       -

head qry.ref.anchors
###
qry_00271       ref_02777       3600
qry_00272       ref_02778       1610
qry_00273       ref_02779       2250
qry_00275       ref_02771       319
qry_00277       ref_02769       969
qry_00278       ref_02768       2490
qry_00288       ref_02762       490
qry_00290       ref_02756       1160
qry_00291       ref_02755       2470
```

**Comment by sc-zhang** [comment]
This tools is designed for adjusting the assembly result of ALLHiC (or other scaffolding tools which can output agp file) by modifying blocks of contigs on chromosomes based on the collinearity between assembly genome and reference genome, both of genomes should be chromosome level assembly.

The files required with this tool are two bed files, one anchors file and one agp file, details of them are:
1. The JCVI package is required to generate ref.bed and qry.bed file from gff3 files with command below,
```bash
python -m jcvi.formats.gff bed --type=mRNA --key=Name ref.gff3.gz -o ref.bed
```
2. Both gff files should be chromosome or pesudo-chromosome level, and if the annotation of the new assembly (query one) is missing, a simple way to use this tool is using gmap to mapping reference CDS to the query genome (chromosome level).
The anchors file is also required JCVI package, with 4 files that qry.bed, qry.cds, ref.bed and ref.cds, then run command below, 
```bash
python -m jcvi.compara.catalog ortholog qry ref
```
More details of JCVI could be found in [JCVI](https://github.com/tanghaibao/jcvi/wiki/MCscan-%28Python-version%29).
3. AGP file is a text file which recorded the contig positions and orients on chromosomes. More details could be found in [AGP file format](https://www.ncbi.nlm.nih.gov/genbank/genome_agp_specification/#FORMAT)

**Comment by s-kyungyong** [comment]
Thank you for the instruction!
